name: Deploy React App to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install and build with aggressive flags
        run: |
          cd frontend
          # Clear any corrupted node_modules
          rm -rf node_modules
          rm -f package-lock.json
          
          # Install with maximum permissiveness
          npm install --legacy-peer-deps --force --no-audit --no-fund
          
          # Force install specific problematic dependencies
          npm install ajv@^8.0.0 ajv-keywords@^5.0.0 --legacy-peer-deps --force --no-save
          
          # Build with all warnings disabled
          CI=false GENERATE_SOURCEMAP=false npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
