cat > .github/workflows/deploy.yml << 'EOF'
name: Deploy React App to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Debug - Check frontend files
        run: |
          echo "=== Frontend directory structure ==="
          ls -la frontend/
          echo "=== Package.json contents ==="
          cat frontend/package.json | grep -A 20 "scripts"

      - name: Install dependencies
        run: |
          cd frontend
          npm install --legacy-peer-deps --force

      - name: Build React app
        run: |
          cd frontend
          npm run build

      - name: Debug - Check build output
        run: |
          echo "=== Build directory contents ==="
          ls -la frontend/build/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
